services:
    victoire_core.widget_siblingsmenu_builder:
        class: Victoire\Widget\SiblingsMenuBundle\SiblingsMenu\Builder\SiblingsMenuBuilder
        arguments: ["@knp_menu.factory"]

    victoire_core.widget_siblingsmenu_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: SiblingsMenu }
    #alias to the form
    victoire.widget.form.siblingsmenu:
        class: Victoire\Widget\SiblingsMenuBundle\Form\WidgetSiblingsMenuType
        tags:
            - { name: form.type , alias: victoire_widget_form_siblingsmenu}

