services:
    victoire_core.twig.widget_siblingsmenu_manager:
        class: Victoire\Widget\SiblingsMenuBundle\Widget\Manager\WidgetSiblingsMenuManager
        arguments: [@service_container]

    widget_siblingsmenu_manager:
        alias: victoire_core.twig.widget_siblingsmenu_manager

    victoire_core.widget_siblingsmenu_builder:
        class: Victoire\Widget\SiblingsMenuBundle\SiblingsMenu\Builder\SiblingsMenuBuilder
        arguments: ["@knp_menu.factory"]
