services:
    victoire_core.widget_siblingsmenu_builder:
        class: Victoire\Widget\SiblingsMenuBundle\SiblingsMenu\Builder\SiblingsMenuBuilder
        arguments: ["@knp_menu.factory"]
    victoire_core.twig.widget_siblingsmenu_manager:
        class: Victoire\Widget\SiblingsMenuBundle\Widget\Manager\WidgetSiblingsMenuManager
        arguments: 
            - "@service_container"

    widget_siblingsmenu_manager:
        alias: victoire_core.twig.widget_siblingsmenu_manager
        
    #alias to the entity
    victoire.widget.siblingsmenu:
        class: Victoire\Widget\SiblingsMenuBundle\Entity\WidgetSiblingsMenu
    #alias to the form
    victoire.widget.form.siblingsmenu:
        class: Victoire\Widget\SiblingsMenuBundle\Form\WidgetSiblingsMenuType
        tags:
            - { name: form.type , alias: victoire_widget_form_siblingsmenu}
        